# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  chat_client:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/chat_client # имя будущего образа
    container_name: client # имя контейнера после запуска
    volumes:
       - ./chat:/data
       - /chat/tmp:/tmp/sockets

  chat_server:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/chat_server # имя будущего образа
    container_name: server # имя контейнера после запуска
    volumes:
       - ./chat:/data
       - /chat/tmp:/tmp/sockets
      
